monitoring/urls.py
# -*- coding: UTF-8 -*-

from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'monitoring'

urlpatterns = [
    # Prihlasovani, odhlasovani
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # Dashboard
    path('', views.IndexView.as_view(), name='index'),
    path('dahboard/brany', views.DashboardBranyView.as_view(), name='dashboard-brany'),
    path('dahboard/zarizeni', views.DashboardZarizeniView.as_view(), name='dashboard-zarizeni'),
    path('dahboard/zpravy', views.DashboardZpravyView.as_view(), name='dashboard-zpravy'),

    # Brany - Gateway
    path('gateway/list', views.GatewayListView.as_view(), name='gateway-list'),
    path('gateway/zpravy', views.GatewayZpravyListView.as_view(), name='gateway-zpravy'),
    path('gateway/create', views.GatewayCreateView.as_view(), name='gateway-create'),
    path('gateway/<int:pk>/edit/', views.GatewayEditView.as_view(), name='gateway-edit'),

    # Zarizeni
    path('zarizeni/list', views.ZarizeniListView.as_view(), name='zarizeni-list'),
    path('zarizeni/zpravy', views.ZarizeniZpravyListView.as_view(), name='zarizeni-vsechny-zpravy'),
    path('zarizeni/<int:zarizeni_pk>/zpravy', views.ZarizeniZpravyListView.as_view(), name='zarizeni-zpravy'),
    path('zarizeni/create', views.ZarizeniCreateView.as_view(), name='zarizeni-create'),
    path('zarizeni/<int:pk>/edit/', views.ZarizeniEditView.as_view(), name='zarizeni-edit'),
    path('zarizeni/<int:pk>/detail/', views.ZarizeniDetailView.as_view(), name='zarizeni-detail'),
    path('zarizeni/<int:pk>/zabbix/', views.ZarizeniZabbixView.as_view(), name='zarizeni-zabbix'),
    path('zarizeni/<int:zarizeni_pk>/zabbix/<int:zabbix_pk>/toggle', views.ZarizeniZabbixToggleView.as_view(), name='zarizeni-zabbix-toggle'),

    # Uzivatele
    path('uzivatel/list', views.UzivatelListView.as_view(), name='uzivatel-list'),
    path('uzivatel/create', views.UzivatelCreateView.as_view(), name='uzivatel-create'),
    path('uzivatel/<int:pk>/edit/', views.UzivatelEditView.as_view(), name='uzivatel-edit'),
    path('uzivatel/<int:pk>/password/', views.UzivatelHesloView.as_view(), name='uzivatel-heslo'),

    # Zabbix
    path('zabbix/list', views.ZabbixListView.as_view(), name='zabbix-list'),
    path('zabbix/create', views.ZabbixCreateView.as_view(), name='zabbix-create'),
    path('zabbix/<int:pk>/edit/', views.ZabbixEditView.as_view(), name='zabbix-edit'),
    path('zabbix/<int:pk>/detail/', views.ZabbixDetailView.as_view(), name='zabbix-detail'),
    path('zabbix/zpravy', views.ZabbixZpravyListView.as_view(), name='zabbix-vsechny-zpravy'),
    path('zabbix/<int:zabbix_pk>/zpravy', views.ZabbixZpravyListView.as_view(), name='zabbix-zpravy'),
    path('zabbix/<int:pk>/zarizeni/', views.ZabbixZarizeniView.as_view(), name='zabbix-zarizeni'),
]

monitoring/forms.py
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AdminPasswordChangeForm

from . import models

class PrihlaseniForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

    def clean(self):
        cleaned_data = self.cleaned_data
        username = cleaned_data['username']
        heslo = cleaned_data['password']
        user = authenticate(username=username, password=heslo)
        if user is not None:
            return cleaned_data 
        else:
            text = _("Nesprávné jméno nebo heslo")
            self.add_error('username', text)
            raise forms.ValidationError(text)


class GatewayForm(forms.ModelForm):
    
    class Meta:
        model = models.Gateway
        fields = ['nazev', 'eui', 'povolena']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nazev'].widget.attrs['class'] = 'form-control'
        self.fields['eui'].widget.attrs['class'] = 'form-control'
        self.fields['povolena'].widget.attrs['class'] = 'form-control'
        self.fields['nazev'].required = True
        self.fields['eui'].required = True


class ZarizeniForm(forms.ModelForm):
    
    class Meta:
        model = models.Zarizeni
        fields = ['nazev', 'devaddr', 'deveui', 'nwkskey', 'appskey', 'povoleno']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nazev'].widget.attrs['class'] = 'form-control'
        self.fields['devaddr'].widget.attrs['class'] = 'form-control'
        self.fields['deveui'].widget.attrs['class'] = 'form-control'
        self.fields['nwkskey'].widget.attrs['class'] = 'form-control'
        self.fields['appskey'].widget.attrs['class'] = 'form-control'
        self.fields['povoleno'].widget.attrs['class'] = 'form-control'
        self.fields['nazev'].required = True
        self.fields['devaddr'].required = True
        self.fields['deveui'].required = True
        self.fields['nwkskey'].required = True
        self.fields['appskey'].required = True


class UserCreateForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'is_active']    

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['first_name'].widget.attrs['class'] = 'form-control'
        self.fields['last_name'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['is_active'].widget.attrs['class'] = 'active'
        self.fields['username'].required = True
        self.fields['password1'].required = True
        self.fields['password2'].required = True
        self.fields['email'].required = True

class UserChangeForm(UserChangeForm):

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password', 'is_active']   

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['first_name'].widget.attrs['class'] = 'form-control'
        self.fields['last_name'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['class'] = 'form-control'
        self.fields['username'].required = True
        self.fields['email'].required = True


class UserPasswordChangeForm(AdminPasswordChangeForm):
    
    class Meta:
        fields = '__all__'


class ZabbixForm(forms.ModelForm):
    
    class Meta:
        model = models.Zabbix
        fields = ['nazev', 'ip_adresa', 'port', 'povolen']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nazev'].widget.attrs['class'] = 'form-control'
        self.fields['ip_adresa'].widget.attrs['class'] = 'form-control'
        self.fields['port'].widget.attrs['class'] = 'form-control'
        self.fields['povolen'].widget.attrs['class'] = 'form-control'
        self.fields['nazev'].required = True

monitoring/views.py
# -*- coding: UTF-8 -*-

from datetime import datetime, timedelta
from django.views import generic
from django.utils.translation import ugettext_lazy as _
from django.core.mail import send_mail
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.urls import reverse_lazy

from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AdminPasswordChangeForm

from . import models
from . import forms
from . import utils

import logging
logger = logging.getLogger(__name__)

# Prihlasovani
class LoginView(generic.FormView):
    form_class = forms.PrihlaseniForm
    template_name = 'monitoring/login.html'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        username = form.cleaned_data['username']
        heslo = form.cleaned_data['password']
        user = authenticate(username=username, password=heslo)
        if user is not None:
            if user.is_active:
                login(self.request, user)
        return HttpResponseRedirect(reverse_lazy('monitoring:index',))


# Dashboard
class IndexView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'monitoring/dashboard/index.html'

class DashboardBranyView(LoginRequiredMixin, generic.ListView):
    model = models.Gateway
    context_object_name = 'gateways'
    template_name = 'monitoring/dashboard/brany.html'

class DashboardZarizeniView(LoginRequiredMixin, generic.ListView):
    model = models.Zarizeni
    context_object_name = 'vsechna_zarizeni'
    template_name = 'monitoring/dashboard/zarizeni.html'

class DashboardZpravyView(LoginRequiredMixin, generic.ListView):
    model = models.Zprava
    context_object_name = 'zpravy'
    template_name = 'monitoring/dashboard/zpravy.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'prijatych': models.Zprava.objects.filter(smer=models.Zprava.RX).count(),
            'odeslanych': models.Zprava.objects.filter(smer=models.Zprava.TX).count(),
            'datovych': models.Zprava.objects.filter(smer=models.Zprava.RX, hex_data__isnull=False).count(),
            'data': models.Data.objects.count()
            })
        return context


###
# BRANA
###


# Výpis bran a jejich informací
class GatewayListView(LoginRequiredMixin, generic.ListView):
    model = models.Gateway
    context_object_name = 'gateways'
    template_name = 'monitoring/gateway/list.html'


# Posledních 10 zpráv ze všech bran
class GatewayZpravyListView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'monitoring/gateway/zpravy.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'zpravy': models.Zprava.objects.all().order_by('-created')[:10]})
        return context

# Přidání brány
class GatewayCreateView(LoginRequiredMixin, generic.CreateView):
    model = models.Gateway
    form_class = forms.GatewayForm
    template_name = 'monitoring/gateway/form.html'

    def get_success_url(self):
        return reverse_lazy('monitoring:gateway-list')

# Editace brány
class GatewayEditView(LoginRequiredMixin, generic.UpdateView):
    model = models.Gateway
    form_class = forms.GatewayForm
    template_name = 'monitoring/gateway/form.html'

    def get_success_url(self):
        return reverse_lazy('monitoring:gateway-list')

###
# ZARIZENI
###


# Výpis zařízení a jejich informací
class ZarizeniListView(LoginRequiredMixin, generic.ListView):
    model = models.Zarizeni
    context_object_name = 'vsechna_zarizeni'
    template_name = 'monitoring/zarizeni/list.html'


# Posledních zpravy zarizeni
class ZarizeniZpravyListView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'monitoring/zarizeni/zpravy.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        zpravy = models.Zprava.objects.filter(data_hodnoty__isnull=False).order_by('-created').distinct()
        if 'zarizeni_pk' in self.kwargs:
            zpravy = zpravy.filter(zarizeni_id=self.kwargs['zarizeni_pk']).order_by('-created').distinct()
        context.update({'zpravy': zpravy[:20]})
        return context


# Přidání zařízení
class ZarizeniCreateView(LoginRequiredMixin, generic.CreateView):
    model = models.Zarizeni
    form_class = forms.ZarizeniForm
    template_name = 'monitoring/zarizeni/form.html'

    def get_success_url(self):
        return reverse_lazy('monitoring:zarizeni-detail', kwargs={'pk': self.object.pk})

    def get_initial(self):
        initial = super().get_initial()
        initial.update({
            'devaddr': utils.generuj_unikatni_klic('devaddr', 32),
            'nwkskey': utils.generuj_unikatni_klic('nwkskey', 128), 
            'appskey': utils.generuj_unikatni_klic('appskey', 128),
        })
        return initial

# Editace zařízení
class ZarizeniEditView(LoginRequiredMixin, generic.UpdateView):
    model = models.Zarizeni
    form_class = forms.ZarizeniForm
    template_name = 'monitoring/zarizeni/form.html'

    def get_success_url(self):
        return reverse_lazy('monitoring:zarizeni-detail', kwargs={'pk': self.object.pk})

# Detail zařízení
class ZarizeniDetailView(LoginRequiredMixin, generic.DetailView):
    model = models.Zarizeni
    template_name = 'monitoring/zarizeni/detail.html'


# Zarizeni a jeho propojeni do Zabbixu
class ZarizeniZabbixView(LoginRequiredMixin, generic.DetailView):
    model = models.Zarizeni
    template_name = 'monitoring/zarizeni/zabbix.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'zabbixy': models.Zabbix.objects.all().order_by('nazev')})
        return context


class ZarizeniZabbixToggleView(LoginRequiredMixin, generic.DetailView):
    model = models.Zarizeni
    pk_url_kwarg = 'zarizeni_pk'

    def post(self, request, *args, **kwargs):
        zarizeni = self.get_object()
        zabbix = get_object_or_404(models.Zabbix, pk=self.kwargs['zabbix_pk'])
        if zarizeni in zabbix.zarizeni.all():
            zabbix.zarizeni.remove(zarizeni)
            messages.add_message(request, messages.ERROR, _("Chyba při ukončování zkoušky"))
            return JsonResponse({'success': True}, status=200)
        else:
            zabbix.zarizeni.add(zarizeni)
            messages.add_message(request, messages.ERROR, _("Chyba při ukončování zkoušky"))
            return JsonResponse({'success': True}, status=200)
        return JsonResponse({'success': False}, status=400)

###
# UZIVATEL
###
   
# Výpis uživatelů
class UzivatelListView(LoginRequiredMixin, generic.ListView):
    model = User
    context_object_name = 'uzivatele'
    template_name = 'monitoring/uzivatel/list.html'
    ordering = ['-is_active', 'username',]


# Přidání uživatele
class UzivatelCreateView(LoginRequiredMixin, generic.CreateView):
    model = User
    form_class = forms.UserCreateForm
    template_name = 'monitoring/uzivatel/form.html'

    def get_success_url(self):
        return reverse_lazy('monitoring:uzivatel-list')

# Editace uživatele
class UzivatelEditView(LoginRequiredMixin, generic.UpdateView):
    model = User
    form_class = forms.UserChangeForm
    template_name = 'monitoring/uzivatel/form.html'

    def get_success_url(self):
        return reverse_lazy('monitoring:uzivatel-list')


# Nastavení hesla uživatele
class UzivatelHesloView(LoginRequiredMixin, generic.FormView):
    form_class = AdminPasswordChangeForm
    template_name = 'monitoring/uzivatel/heslo.html'

    def dispatch(self, request, *args, **kwargs):
        self.user = get_object_or_404(User, pk=self.kwargs['pk'])
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('monitoring:uzivatel-list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.user
        return kwargs

    def form_valid(self, form):
        self.user.set_password(form.cleaned_data['password1'])
        self.user.save()
        return HttpResponseRedirect(self.get_success_url())



###
# ZABBIX
###

# Výpis zabbixu a jejich informací
class ZabbixListView(LoginRequiredMixin, generic.ListView):
    model = models.Zabbix
    context_object_name = 'vsechny_zabbixy'
    template_name = 'monitoring/zabbix/list.html'


# Přidání zabbixu
class ZabbixCreateView(LoginRequiredMixin, generic.CreateView):
    model = models.Zabbix
    form_class = forms.ZabbixForm
    template_name = 'monitoring/zabbix/form.html'

    def get_success_url(self):
        return reverse_lazy('monitoring:zabbix-detail', kwargs={'pk': self.object.pk})

# Editace zabbixu
class ZabbixEditView(LoginRequiredMixin, generic.UpdateView):
    model = models.Zabbix
    form_class = forms.ZabbixForm
    template_name = 'monitoring/zabbix/form.html'

    def get_success_url(self):
        return reverse_lazy('monitoring:zabbix-detail', kwargs={'pk': self.object.pk})


# Detail zabbixu
class ZabbixDetailView(LoginRequiredMixin, generic.DetailView):
    model = models.Zabbix
    template_name = 'monitoring/zabbix/detail.html'

# Posledních 10 zpráv odeslaných do zabbixu
class ZabbixZpravyListView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'monitoring/zabbix/zpravy.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        zpravy = models.ZabbixSenderLog.objects.all().order_by('-created')
        if 'zabbix_pk' in self.kwargs:
            zpravy = zpravy.filter(zabbix_id=self.kwargs['zabbix_pk']).order_by('-created').distinct()

monitoring/templates/monitoring/gateway/form.html
{% extends "monitoring/gateway/list.html" %}

{% load i18n %}

{% block content %}
    <div class="container-fluid" id="container-wrapper">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">{% trans "Brány" %}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="card mb-4">
                <div class="card-header py-3 justify-content-between">
                    <div class="row">
                        <div class="col-lg-6">
                            <h6 class="m-0 font-weight-bold text-primary">{% if form.instance.pk %}{% trans "Upravit bránu" %}{% else %}{% trans "Nová brána" %}{% endif %}</h6>
                        </div>
                    </div>
                </div>
                <div class="table-responsive p-3">
                    <form 
                        action="#"
                        method="post" 
                        id="gateway-form" 
                        role="form" 
                        class="form-horizontal">
                        {{ form.media.css }}
                        {{ form.media.js }}
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary form-control">{% trans "Uložit" %}</button>
                    </form>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

monitoring/templates/monitoring/gateway/list.html
{% extends "monitoring/index.html" %}

{% load i18n %}

{% block content %}
    <div class="container-fluid" id="container-wrapper">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">{% trans "Brány" %}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <div class="card mb-4">
                <div class="card-header py-3 justify-content-between">
                    <div class="row">
                        <div class="col-lg-6">
                            <h6 class="m-0 font-weight-bold text-primary">{% trans "Seznam bran" %}</h6>
                        </div>
                        <div class="col-lg-6 pull-right">
                            <a href="{% url 'monitoring:gateway-create' %}" class='btn btn-sm btn-success'><i class="fas fa-plus"></i>&nbsp;{% trans "Přidat" %}</a>
                        </div>
                    </div>
                </div>
                <div class="table-responsive p-3">
                    <table class="table align-items-center table-flush" id="brany-dataTable">
                    <thead class="thead-light">
                        <tr>
                            <th>{% trans "Název" %}</th>
                            <th>{% trans "EUI" %}</th>
                            <th>{% trans "IP adresa" %}</th>
                            <th>{% trans "Povolena" %}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for gateway in gateways %}
                            <tr>
                                <td>{{ gateway.nazev }}&nbsp;<a href="{% url 'monitoring:gateway-edit' gateway.pk %}"><i class="far fa-edit"></i></a></td>
                                <td>{{ gateway.eui }}</td>
                                <td>{{ gateway.ip_adresa }}</td>
                                <td><span class="badge badge-{{ gateway.povolena|yesno:_("success,danger") }}">{{ gateway.povolena|yesno:_("Povolena,Zakázána") }}</span></td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="4">
                                    {% trans "Není nastavena žádná brána" %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="card mb-4">
                <div class="card-header py-3 justify-content-between">
                    <div class="row">
                        <div class="col-lg-6">
                            <h6 class="m-0 font-weight-bold text-primary">{% trans "Posledních 10 zpráv" %}</h6>
                        </div>
                        <div class="col-lg-6 pull-right">
                            <a href="#" class='btn btn-sm btn-info reload-content'><i class="fas fa-sync"></i></i>&nbsp;{% trans "Obnovit" %}</a>
                        </div>
                    </div>
                </div>
                <div class="panel-body" data-autoload='true' id="zpravy-list" data-content-url="{% url 'monitoring:gateway-zpravy' %}"></div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script>
        $(document).ready(function () {
            $('#brany-dataTable').DataTable();
        });
    </script>
{% endblock %}

monitoring/templates/monitoring/gateway/zpravy.html
{% load i18n %}

<div class="table-responsive p-3">
    <table class="table align-items-center table-flush" id="brany-dataTable">
        <thead class="thead-light">
            <tr>
                <th>{% trans "Směr" %}</th>
                <th>{% trans "Čas" %}</th>
                <th>{% trans "Brána" %}</th>
                <th>{% trans "Typ zprávy" %}</th>
                <th>{% trans "Data" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for zprava in zpravy %}
                <tr>
                    <td>{{ zprava.smer }}&nbsp;{% if zprava.smer == 'RX'%}<i class="fas fa-arrow-down fa-green"></i>{% else %}<i class="fas fa-arrow-up fa-red"></i>{% endif %}</td>
                    <td>{{ zprava.created|date:'H:i:s' }}</td>
                    <td>{{ zprava.gateway.nazev }}</td>
                    <td>{{ zprava.get_typ_zpravy_display }}</td>
                    <td>{{ zprava.payload|default:""|safe|truncatechars:30 }}{% if zprava.payload %}&nbsp;<i class="far fa-comment-dots" data-toggle="popover" data-placement="left" data-trigger="click" data-content="{{ zprava.payload|addslashes }}"></i>{% endif %}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="4">
                        {% trans "Žádné zprávy" %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<script>
    $(function () {
        $('[data-toggle="popover"]').popover();
    });
</script>